#!/usr/bin/env bash

rclone copy .config/rclone/ s3repo:myubuntu/.config/rclone
rclone copy .aws/ s3repo:myubuntu/.aws
rclone copy .s3cfg s3repo:myubuntu/

rclone copy .ssh/ s3repo:myubuntu/.ssh

rclone copy .gitconfig s3repo:myubuntu/
rclone copy .zsh_history s3repo:myubuntu/
